webapp/media/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Length


class CommentForm(Form):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
    )
    text = TextAreaField(u'Comment', validators=[DataRequired()])

class PostForm(Form):
    title = StringField('Title', [
        DataRequired(),
        Length(max=255)
    ])
    text = TextAreaField('Content', [DataRequired()])

class MovieForm(Form):
    title = StringField('Title', [
        DataRequired(),
        Length(max=255)
        ])
    director = StringField('Director')
    actors = StringField('Cast', [Length(max=255)])
    year = IntegerField('Year')
    plot = TextAreaField('Plot', [Length(max=512)])
    poster_url = StringField('Poster URL', [Length(max=255)])
    rating_source = StringField('Rating Source', [Length(max=128)])
    rating = StringField('Rating', [Length(max=128)])

    def omdb_factory(self, omdb_data):
        """
        Populate the form fields with data from the OMDB API response.

        Args:
            omdb_data (dict): The OMDB API response data.
        """
        self.title.data = omdb_data.get('Title')
        self.director.data = omdb_data.get('Director')
        self.actors.data = omdb_data.get('Actors')
        self.year.data = omdb_data.get('Year')
        self.plot.data = omdb_data.get('Plot')
        self.poster_url.data = omdb_data.get('Poster')
        the_ratings = omdb_data.get('Ratings')
        self.rating_source.data = None
        # Check to see if there is a Rotten Tomatoes rating in the list of ratings
        # If there is, set the rating_source and rating fields accordingly
        # If there is no Rotten Tomatoes rating, check for an Internet Movie Database rating
        if the_ratings:
            for rating in the_ratings:
                if rating.get('Source') == 'Rotten Tomatoes':
                    self.rating_source.data = 'Rotten Tomatoes'
                    self.rating.data = rating.get('Value')
                    break
            if self.rating_source.data is None:
                for rating in the_ratings:
                    if rating.get('Source') == 'Internet Movie Database':
                        self.rating_source.data = 'Internet Movie Database'
                        self.rating.data = rating.get('Value')
                        break
        else:
            self.rating_source.data = None
            self.rating.data = None
        

webapp/__init__.py
from flask import Flask

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()


def create_app(the_config):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        the_config: the python path of the config object,
                     e.g. project.config.ProdConfig
    """
    app = Flask(__name__)
    app.config.from_object(the_config)

    db.init_app(app)
    migrate.init_app(app, db)

    from .media import create_module as media_create_module
    from .main import create_module as main_create_module
    media_create_module(app)
    main_create_module(app)

    return app

webapp/main/__init__.py
def create_module(app, **kwargs):
    from .controllers import main_blueprint
    app.register_blueprint(main_blueprint)

webapp/main/controllers.py
from flask import Blueprint, redirect, url_for, render_template, flash, request, session
import json
from datetime import datetime
from .omdb_access import querry_omdb_api
from ..media.forms import MovieForm
from ..media.models import Movie, Actor, Writer
from .. import db

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates'
)


@main_blueprint.route('/', methods=['GET', 'POST'])
def home():
    """The home page of the web app."""
    if request.method == 'POST':
        # Handle POST request
        # Access form data
        form_data = request.form
        media_title = form_data.get('Title')
        search_type = form_data.get('radioSearchSelect')
        if search_type.strip() == 'OMDB':
            # Call OMDB API with the selected search type
            # Example: Call the API with the title and search type
            # response = call_omdb_api(media_title, search_type)
            media_type = form_data.get('radioOmdbType')
            year = form_data.get('Year')
            if len(year) > 0:
                response = querry_omdb_api(media_title, type=media_type, year=year)
            else:
                response = querry_omdb_api(media_title, type=media_type)
            # Check if the response is valid
            if response.get('Response') == 'True':
                a_movie = Movie()
                a_movie.omdb_factory(response)    

                # Check if the movie is already in the local database
                inTable = db.session.query(Movie).filter(Movie.title == a_movie.title).first() 
                if inTable:
                    flash('{0} already in table'.format(a_movie.title))
                    # a_movie = inTable
                session['omdb_result'] = json.dumps(response)                          
                return render_template('review.html', movie=a_movie)
            else:
                # figure out how to send flash messages
                flash("Error: When searching for {0}, OMDB returned {1}".format(media_title, response.get('Error')))
            return render_template('home.html', results="Placeholder response")
        else:
            # Look up this title in the local database using SQLAlchemy
            inTable = db.session.query(Movie).filter(Movie.title == media_title).first() 
            if inTable:
                return redirect(url_for('main.movie_detail', movie_id=inTable.id))                
            else:
                flash("Sorry! {0} not found in local database.".format(media_title))
            return render_template('home.html')
        # If no search type is selected, return an error message or redirect    
    else:
        # Handle GET request
        return render_template('home.html')    

@main_blueprint.route('/review', methods=['GET', 'POST'])
def review():
    """The review page of the web app."""
    
    if request.method == 'POST':
        # Handle POST request
        # Access form data
        form_data = request.form
        media_title = form_data.get('Title')

        omdb_result = json.loads(session.get('omdb_result', '{}'))
        # new_movie = session.get('movie', None)
        new_movie = Movie()
        new_movie.omdb_factory(omdb_result)
        if new_movie is None:
            flash("Error: No movie object found in Flask session.")
            return render_template('home.html')

        if new_movie.title != media_title:
            flash("Error: Flask stored OMDB Movie title {0} does not match review form movie title {1}.".format(new_movie.title, media_title))
            return render_template('home.html')
            
        new_movie.PersonalRating = int(form_data.get('PersonalRating'))
        new_movie.DateViewed = datetime.strptime(form_data.get('DateViewed'), '%Y-%m-%d')

        # Check if the movie is already in the local database
        inTable = db.session.query(Movie).filter(Movie.title == new_movie.title).first()
        if inTable:
            flash('{0} already in table'.format(new_movie.title))
            inTable.UpdateUsing(new_movie)
            db.session.commit()
        else:
            db.session.add(new_movie)
            db.session.commit()
            flash("Success: Entered {0} into local Db".format(media_title))

        session['movie'] = None        
        return render_template('home.html')
    
    # If the form is not submitted, render the review page with the form
    return render_template('review.html')
        
@main_blueprint.route('/listings', methods=['GET', 'POST'])
def listings():
    """The page lisitng contents of local db the web app."""
    # Use SQLAlchemy to query the database and get the list of movies
    # Take advantage of the pagination feature of Flask-SQLAlchemy
    # Example: Get the first 10 movies
    page_index = request.args.get('page', 1, type=int)
    page_of_movies = db.session.query(Movie).order_by(Movie.title).paginate(page=page_index, per_page=10)

    if request.method == 'POST':
        print("POST request received")
        # Handle POST request
        return render_template('home.html')

    return render_template('db_listing.html', page=page_of_movies)

@main_blueprint.route('/movie/<int:movie_id>', methods=['GET', 'POST'])
def movie_detail(movie_id):
    """The page showing details of a movie."""
    # Use SQLAlchemy to query the database and get the movie details
    movie = db.session.query(Movie).get(movie_id)
    if not movie:
        flash("Error: Movie with ID {0} not found.".format(movie_id))
        return redirect(url_for('main.listings'))
    
    if request.method == 'POST':
        flash("Todo: Handle POST request for movie detail page")
        return render_template('home.html')

    return render_template('movie_detail.html', movie=movie)

@main_blueprint.route('/movie/<int:movie_id>/delete', methods=['POST'])
def delete_movie(movie_id):
    """Delete a movie from the database."""
    # Use SQLAlchemy to query the database and delete the movie
    movie = db.session.query(Movie).get(movie_id)
    if not movie:
        flash("Error: Movie with ID {0} not found.".format(movie_id))
        return render_template('home.html')

    # Add bootstrap modal confirmation
    # if request.method == 'POST':
    #     # Handle POST request

    db.session.delete(movie)
    db.session.commit()
    flash("Success: Deleted movie with ID {0}".format(movie_id))
    return render_template('home.html')

@main_blueprint.route('/movie/<int:movie_id>/edit', methods=['GET', 'POST'])
def edit_movie(movie_id):
    """Edit a movie in the database."""
    # Use SQLAlchemy to query the database and get the movie details

    if request.method == 'GET':
            movie = db.session.query(Movie).get(movie_id)
            if not movie:
                flash("Error: Movie with ID {0} not found.".format(movie_id))
                return render_template('home.html')
            # Render the edit form with the movie details
            return render_template('edit_movie.html', movie=movie)
    else:
        # Handle POST request
        # Access form data
        form_data = request.form
        media_title = form_data.get('Title')
        Movie.query.filter_by(id=movie_id).first().update(
            title='New Title',
            year=2023,
            rating=8.5,
            genre='Action',
            director='New Director',
            writer='New Writer',
            actors='New Actors',
            plot='New Plot',
            poster='New Poster URL'
        )
        db.session.commit()
        flash("Success: Updated movie with ID {0}".format(movie_id))
        return render_template('home.html')


    

    

webapp/media/__init__.py
def create_module(app, **kwargs):
    from .controllers import media_blueprint
    app.register_blueprint(media_blueprint)

webapp/media/controllers.py
import datetime
from sqlalchemy import desc, func
from flask import render_template, Blueprint, flash, redirect, url_for, current_app, abort
from .models import db, Actor, Movie

from .forms import MovieForm

media_blueprint = Blueprint(
    'media',
    __name__,
    template_folder='../templates/media',
    url_prefix="/media"
)


# def sidebar_data():
#     recent = Post.query.order_by(Post.publish_date.desc()).limit(5).all()
#     top_tags = db.session.query(
#         Tag, func.count(tags.c.post_id).label('total')
#     ).join(tags).group_by(Tag).order_by(desc('total')).limit(5).all()

#     return recent, top_tags


@media_blueprint.route('/')
@media_blueprint.route('/<int:page>')
def home(page=1):
    movies = Movie.query.all() 

    return render_template(
        'home.html',
        movies=movies
    )


@media_blueprint.route('/create', methods=['GET', 'POST'])
def create_entry():
    form = MovieForm()
    if form.validate_on_submit():
        new_entry = Movie()
        new_entry.title = form.title.data
        new_entry.director = form.director.data
        new_entry.actors = package_cast(form.actors.data)
        new_entry.year = form.year
        db.session.add(new_entry)
        db.session.commit()
        flash('Entry added', 'info')
        return redirect(url_for('.read_entry', movie_id=new_entry.id))   # this may not exist yet
    return render_template('create.html', form=form)

def package_cast(data):
    raw_cast = data
    actor_list = raw_cast.split(",")
    actors = []
    for str_actor in actor_list:
        actor = Actor()
        actor.define_from_actor_fullname(str_actor)
        actors.append(actor)
    return actors

@media_blueprint.route('/read/<int:movie_id>', methods=['GET', 'POST'])
def read_entry(movie_id):
    if movie_id < 0:
        movie = Movie(title='New Entry')
    else:
        movie = Movie.query.get_or_404(movie_id)

    form = MovieForm()
    form.title.data = movie.title
    form.director.data = movie.director
    form.actors.data = movie.actors_to_string()
    form.year.data = movie.year
    return render_template('read.html', form=form, movie=movie)

@media_blueprint.route('/update/<int:movie_id>', methods=['GET', 'POST'])
def update_entry(movie_id):
    if movie_id < 0:
        movie = Movie(title='Provide Entry')
    else:
        movie = Movie.query.get_or_404(movie_id)

    form = MovieForm()
    if form.validate_on_submit():
        movie.title = form.title.data
        movie.director = form.director.data
        movie.actors = package_cast(form.actors.data)
        movie.year = form.year.data
        movie.DateViewed = datetime.datetime.now()
        db.session.update(movie)
        db.session.commit()
        return redirect(url_for('.display', movie_id=movie.id))
    form.title.data = movie.title
    form.director.data = movie.director
    form.actors.data = movie.actors_to_string()
    the_Actors = movie.actors_to_string()
    form.year.data = movie.year
    return render_template('update.html', form=form, movie=movie)
    
@media_blueprint.route('/delete/<int:movie_id>', methods=['GET', 'POST'])
def delete_entry(movie_id):
    if movie_id < 0:
        movie = Movie(title='Provide Entry')
    else:
        movie = Movie.query.get_or_404(movie_id)

    form = MovieForm()
    if form.validate_on_submit():
        movie.title = form.title.data
        movie.director = form.director.data
        movie.actors = package_cast(form.actors.data)
        movie.year = form.year.data
        db.session.delete(movie)
        db.session.commit()
        return redirect(url_for('.home', movie_id=movie.id))
    form.title.data = movie.title
    form.director.data = movie.director
    form.actors.data = movie.actors_to_string()
    form.year.data = movie.year
    return render_template('delete.html', form=form, movie=movie)

# @media_blueprint.route('/post/<int:post_id>', methods=('GET', 'POST'))
# def post(post_id):
#     form = CommentForm()

#     if form.validate_on_submit():
#         new_comment = Comment()
#         new_comment.name = form.name.data
#         new_comment.text = form.text.data
#         new_comment.post_id = post_id
#         try:
#             db.session.add(new_comment)
#             db.session.commit()
#         except Exception as e:
#             flash('Error adding your comment: %s' % str(e), 'error')
#             db.session.rollback()
#         else:
#             flash('Comment added', 'info')
#         return redirect(url_for('blog.post', post_id=post_id))

    # post = Post.query.get_or_404(post_id)
    # tags = post.tags
    # comments = post.comments.order_by(Comment.date.desc()).all()
    # recent, top_tags = sidebar_data()

    # return render_template(
    #     'post.html',
    #     post=post,
    #     tags=tags,
    #     comments=comments,
    #     recent=recent,
    #     top_tags=top_tags,
    #     form=form
    # )


# @media_blueprint.route('/tag/<string:tag_name>')
# def posts_by_tag(tag_name):
#     tag = Tag.query.filter_by(title=tag_name).first_or_404()
#     posts = tag.posts.order_by(Post.publish_date.desc()).all()
#     recent, top_tags = sidebar_data()

#     return render_template(
#         'tag.html',
#         tag=tag,
#         posts=posts,
#         recent=recent,
#         top_tags=top_tags
#     )


# @media_blueprint.route('/user/<string:username>')
# def posts_by_user(username):
#     user = User.query.filter_by(username=username).first_or_404()
#     posts = user.posts.order_by(Post.publish_date.desc()).all()
#     recent, top_tags = sidebar_data()

#     return render_template(
#         'user.html',
#         user=user,
#         posts=posts,
#         recent=recent,
#         top_tags=top_tags
#     )

webapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}For The Record{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
</head>
<body>
{% include 'navbar.html' %}
<div class="container-fluid">
    <div class="row row-lg-6">
        <div class="col">
            {% block head %}
            {% include 'head.html' %}
            {% endblock %}
        </div>
    </div>
    {% include 'messages.html' %}
    {% block body %}
    <div class="row row-lg-12">
        
            {% block leftbody %}
            {% endblock %}        
        
            {% block rightbody %}            
            {% endblock %}
        
    </div>
    {% endblock %}
    {% include 'footer.html' %}
</div>
</body>
{% block js %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    </body>
</html>

webapp/templates/db_listing.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}
{% block title %}For The Record{% endblock %}
{% block leftbody %}
<div class="col-12">  
  <div class="card ">
    <div class="card-body">
      <h5 class="card-title">My Media Log</h5>

      <nav aria-label="Page navigation">
        <ul class="pagination">
          {% if page.has_prev %}
          <li class="page-item"><a class="page-link" href="{{ url_for('main.listings', page=page.prev_num) }}">Previous</a></li>
          {% else %}
          <li class="page-item disabled"><a class="page-link">Previous</a></li>
          {% endif %}
          {% for index in range(1, page.pages+1) %}
          <li class="page-item {% if index == page.page %}active{% endif %}">
            <a class="page-link" href="{{ url_for('main.listings', page=index) }}">{{ index }}</a>          
          {% endfor %}
          {% if page.has_next %}
          <li class="page-item"><a class="page-link" href="{{ url_for('main.listings', page=page.next_num) }}">Next</a></li>
          {% else %}
          <li class="page-item disabled"><a class="page-link">Next</a></li>
          {% endif %}
        </ul>
      </nav>
      
      {% for movie in page.items if movie.title%}
      <div class="row">
        <div class="col-md-10">
          <p class="card-text"><a class="text-dark" href="{{url_for('main.movie_detail', movie_id=movie.id)}}">{{ movie.title }}</a></p>
        </div>
      </div>
      {% endfor %}    
    </div>
  </div>
</div>

{% endblock %}

webapp/templates/footer.html
<div class="row">
    <div class="col-6 offset-1 text-left">
        <small><em>
            A Flask web app by S. Trickey - 2025
        </em></small>
        </div>            
</div>

webapp/templates/head.html
<div class="container bg-info rounded">
    <center>
    <i class="fas fa-comments fa-5x"></i>
    <h1><a class="text-white" href="{{ url_for('main.home') }}">For The Record</a></h1>
    <p>A record of media consumption!</p>
    </center>
</div>

webapp/templates/home.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}
{% block title %}For The Record{% endblock %}
{% block leftbody %}
<div class="col-12">  
  <div class="card ">
    <div class="card-body">
      <h5 class="card-title">Media Search</h5>
      <p class="card-text">Pick whether to search OMDB or the local db then enter a movie or show title.</p>
      <form method="POST" action="/">
        <div class="row justify-content-md-center">  
          <div class="col-md-10">              
            <div class="input-group">
              <span class="input-group-text">Title</span>
              <input class="form-control" name="Title" aria-label="A Title" id="formTitleEntry" placeholder="Enter a title" type="text" aria-describedby="button-search">
              <button class="btn btn-outline-primary" type="submit" id="button-search">Search</button>
            </div>   
          </div>
        </div>
        <div class="row justify-content-md-center">  
          <div class="col-md-10">              
            <div class="input-group">
              <span class="input-group-text">Year</span>
              <input class="form-control" name="Year" aria-label="A Year" id="formYearEntry" placeholder="Enter a year (optional)" type="text" aria-describedby="button-search">                
            </div>   
          </div>
        </div>   
        <p> </p>
        <div class="row justify-content-md-center g-2" >
          <div class="col-md-5">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">OMDB Search Options</h5>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="radioSearchSelect" id="radioOmdbSearch" value="OMDB" checked>
                  <label class="form-check-label" for="radioOmdbSearch">OMDB Source</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="radioOmdbType" id="radioMovieType" value="movie" checked>
                  <label class="form-check-label" for="radioLocalSearch">Movie</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="radioOmdbType" id="radioSeriesType" value="series">
                  <label class="form-check-label" for="radioLocalSearch">TV Series</label>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-3"></div>
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Local db Search</h5>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="radioSearchSelect" id="radioLocalSearch" value="Local">
                <label class="form-check-label" for="radioLocalSearch">Local db Search</label>
              </div>
            </div>
          </div>          
        </div>                  
      </form>
    </div>
  </div>
</div>

{% endblock %}

webapp/templates/macros.html
<!--
{% macro render_pagination(pagination, endpoint) %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if pagination.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('media.home', page=pagination.prev().page) }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}
        {% for page in pagination.iter_pages() %}
        {% if page %}
        {% if page != pagination.page %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
        </li>
        {% else %}
        <li class="page-item active">
            <a class="page-link" href="">{{ page }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="page-item">
            <a class="page-link">…</a>
        <li>
            {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('media.home', page=pagination.next().page) }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endmacro %}
-->

{% macro render_movie_detail(movie) %}
<div class="row">
    <div class="col">                        
        <div class="input-group">
            <span class="input-group-text">Title</span>
            <input class="form-control" name="Title" aria-label="A Title" id="TitleEntry" type="text" value="{{movie.title}}">                
        </div> 
    </div>
</div>
<div class="row">
    <div class="col"> 
        <div class="input-group">
            <span class="input-group-text">Director</span>
            <input class="form-control" name="Director" aria-label="A Director" id="Director" type="text" value="{{movie.director}}">                
        </div>
    </div>
</div>
<div class="row">
    <div class="col"> 
        <div class="input-group">
            <span class="input-group-text">Writer</span>
            <input class="form-control" name="Writer" aria-label="A Writer" id="Writer" type="text" value="{{movie.writers_to_string()}}">                
        </div>
    </div>
</div>
<div class="row">
    <div class="col">  
        <div class="input-group">
            <span class="input-group-text">Cast</span>
            <input class="form-control" name="Title" aria-label="A Title" id="actors" type="text" value="{{movie.actors_to_string()}}">                
        </div>
    </div>
</div>  
<div class="row row-cols-2">
    <div class="col-6">
        <div class="input-group">
            <span class="input-group-text">Year</span>
            <input class="form-control" name="Year" aria-label="A Year" id="year" type="text" value="{{movie.year}}">                
        </div> 
    </div>
    <div class="col-6">
        <div class="input-group">
            <span class="input-group-text">{{movie.RatingSource}}</span>
            <input class="form-control" name="Rating" aria-label="A Rating" id="Rating" type="text" value="{{movie.RatingValueString}}">                
        </div>
    </div>                        
    <div class="col-6">
        <div class="input-group">
            <span class="input-group-text">Personal Rating</span>
            <input class="form-control" name="PersonalRating" aria-label="A personalRating" id="PersonalRating" type="text" value="{{movie.PersonalRating}}">                
        </div>
    </div>
    <div class="col-6">
        <div class="input-group date" id="datepicker">
            <span class="input-group-text">Date Viewed</span>
            <input type="date" class="form-control" name="DateViewed" id="DateViewed" aria-label="A Date Viewed" value="{{movie.DateViewed.strftime('%Y-%m-%d')if movie.DateViewed else '2000-11-28'}}">
        </div>
    </div>
</div> 
<br>                    
<h5 class="card-title">Plot Synopsis</h5>
<p class="card-text">{{movie.plot}}</p>
{% endmacro %}

{% macro render_entries(movies, pagination=True) %}
{% if pagination %}
{% set _movies = movies.items %}
{% else %}
{% set _movies = movies %}
{% endif %}

{% for movie in _movies %}
<div >
    <h3>
        <a class="text-dark" href="{{ url_for('media.update_entry', movie_id=movie.id) }}">{{ movie.title }}</a>
    </h3>
</div>
<div class="row">
    Director: {{ movie.director.first_name | truncate(500) | safe }} {{ movie.director.last_name | truncate(500) | safe }}
</div>
<div class="row"></div>
    Cast: {% for actor in movie.actors %}
    {{actor.first_name}} {{actor.last_name}}, 
    {% endfor %}
</div>
{% endfor %}
{% endmacro %}

{% macro render_form_entry(form) %}
{% set _form = form %}
<div class="form-group">
    {{ form.title.label }}
    {% if form.title.errors %}
    {% for e in form.title.errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {{ form.title(class_='form-control') }}
</div>
<div class="form-group">
    {{ form.director.label }}
    {% if form.director.errors %}
    {% for e in form.director.errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {{ form.director(id="editor", class_='form-control') }}
</div>
<div class="form-group">
    {{ form.actors.label }}
    {% if form.actors.errors %}
    {% for e in form.actors.errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {{ form.actors(id="editor", class_='form-control') }}
</div>
<div class="form-group">
    {{ form.year.label }}
    {% if form.year.errors %}
    {% for e in form.year.errors %}
    <p class="help-block">{{ e }}</p>
    {% endfor %}
    {% endif %}
    {{ form.year(id="editor", class_='form-control') }}
</div>
{% endmacro %}

webapp/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

webapp/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('main.home')}}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.listings')}}">Review<span class="sr-only">(current)</span></a>
            </li>
            <!-- 
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('media.read_entry', movie_id=-1)}}">Create<span class="sr-only">(current)</span></a>
            </li>
                        
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('media.update_entry', movie_id=-1)}}">Update<span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{url_for('media.delete_entry', movie_id=-1)}}">Delete<span class="sr-only">(current)</span></a>
            </li>
            -->
        </ul>
    </div>
</nav>